//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsMatching.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordsMatching.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I
        ///a
        ///ad
        ///ah
        ///al
        ///am
        ///an
        ///ar
        ///as
        ///at
        ///au
        ///ax
        ///ba
        ///be
        ///bi
        ///by
        ///cm
        ///co
        ///do
        ///ed
        ///eg
        ///eh
        ///el
        ///en
        ///er
        ///et
        ///ex
        ///fa
        ///ft
        ///go
        ///gu
        ///ha
        ///he
        ///hi
        ///ho
        ///id
        ///if
        ///in
        ///is
        ///it
        ///kg
        ///km
        ///ko
        ///ky
        ///la
        ///lp
        ///ma
        ///me
        ///mi
        ///mo
        ///mr
        ///ms
        ///mu
        ///my
        ///na
        ///no
        ///nu
        ///ny
        ///od
        ///of
        ///oh
        ///ok
        ///on
        ///op
        ///or
        ///os
        ///ow
        ///ox
        ///pa
        ///pc
        ///pe
        ///pi
        ///po
        ///pu
        ///ra
        ///re
        ///sa
        ///se
        ///so
        ///to
        ///tv
        ///uh
        ///un
        ///up
        ///us
        ///ut
        ///va
        ///vi
        ///we
        ///wi
        ///xi
        ///yd
        ///ye
        ///yo
        ///yr
        ///abc
        ///abe
        ///ace
        ///act
        ///add
        ///ado
        ///aft
        ///age
        ///ago
        ///aha
        ///aid
        ///ail
        ///aim
        ///air
        ///alb
        ///ale
        ///ali
        ///all
        ///alm
        ///alp
        ///alt
        ///ama
        ///ami
        ///amp
        ///amt
        ///amu
        ///amy
        ///ana
        ///and
        ///ani
        ///ann
        ///ant
        ///any
        ///ape
        ///apo
        ///apt
        ///arc
        ///are
        ///ark
        ///arm
        ///art
        ///ash
        ///ask
        ///asp
        ///ass
        ///ate
        ///aug
        ///auk
        ///aut
        ///ave
        ///awe
        ///awl
        ///awn
        ///axe
        ///aye
        ///baa
        ///bad
        ///b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
    }
}
